// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface PageContentMarketingHeroV1Block {
  _type: "marketing_hero";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "primary_cta_label"?: string | null;
  "primary_cta_url"?: string | null;
  "secondary_cta_label"?: string | null;
  "secondary_cta_url"?: string | null;
  "image"?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } } | null;
  "centered"?: boolean | null;
}

export type PageContentMarketingHeroBlock = PageContentMarketingHeroV1Block;

export interface PageContentMarketingConversationV1Block {
  _type: "marketing_conversation";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "messages": { "speaker": "you" | "mefinx"; "text": string }[];
  "caption"?: string | null;
}

export type PageContentMarketingConversationBlock = PageContentMarketingConversationV1Block;

export interface PageContentMarketingFeaturesV1Block {
  _type: "marketing_features";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline": string;
  "subheadline"?: string | null;
  "features": { "icon": "chat" | "graph" | "filter" | "search" | "pin" | "calendar" | "offline" | "undo" | "lock" | "sparkle" | "phone" | "contacts" | "users" | "heart" | "clock" | "star"; "title": string; "description": string }[];
}

export type PageContentMarketingFeaturesBlock = PageContentMarketingFeaturesV1Block;

export interface PageContentMarketingFaqV1Block {
  _type: "marketing_faq";
  _version: 1;
  _key: string;
  "anchor_id"?: string | null;
  "headline"?: string | null;
  "items": { "question": string; "answer": string }[];
}

export type PageContentMarketingFaqBlock = PageContentMarketingFaqV1Block;

export type PageContentBlock = PageContentMarketingHeroBlock | PageContentMarketingConversationBlock | PageContentMarketingFeaturesBlock | PageContentMarketingFaqBlock;

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PageContentBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
  }
}